#!/bin/bash

# =============================================================================
# VPN Server Setup Script (OpenVPN & WireGuard)
# Compatible with Ubuntu 22.04 LTS
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration variables
VPN_TYPE=""
SERVER_IP=""
VPN_PORT=""
CLIENT_NAME="client1"
OPENVPN_DIR="/etc/openvpn"
WIREGUARD_DIR="/etc/wireguard"

# =============================================================================
# Utility Functions
# =============================================================================

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}"
}

warn() {
    echo -e "${YELLOW}[WARNING] $1${NC}"
}

error() {
    echo -e "${RED}[ERROR] $1${NC}"
    exit 1
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root. Use: sudo $0"
    fi
}

get_server_ip() {
    # Try to get public IP, fallback to local IP
    SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || curl -s ipinfo.io/ip 2>/dev/null || ip route get 1.1.1.1 | awk '{print $7; exit}')
    if [[ -z "$SERVER_IP" ]]; then
        error "Could not determine server IP address"
    fi
    log "Detected server IP: $SERVER_IP"
}

update_system() {
    log "Updating system packages..."
    apt update && apt upgrade -y
    apt install -y curl wget ufw iptables-persistent
}

enable_ip_forwarding() {
    log "Enabling IP forwarding..."
    
    # Enable IP forwarding permanently
    echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
    echo 'net.ipv6.conf.all.forwarding=1' >> /etc/sysctl.conf
    
    # Apply immediately
    sysctl -p
    
    log "IP forwarding enabled"
}

# =============================================================================
# OpenVPN Setup Functions
# =============================================================================

install_openvpn() {
    log "Installing OpenVPN..."
    
    apt install -y openvpn easy-rsa
    
    # Setup PKI directory
    make-cadir $OPENVPN_DIR/easy-rsa
    cd $OPENVPN_DIR/easy-rsa
    
    log "OpenVPN installed successfully"
}

configure_openvpn_pki() {
    log "Configuring OpenVPN PKI (Public Key Infrastructure)..."
    
    cd $OPENVPN_DIR/easy-rsa
    
    # Initialize PKI
    ./easyrsa init-pki
    
    # Build CA (Certificate Authority) - non-interactive
    echo -e "\n\n\n\n\n\n\n" | ./easyrsa build-ca nopass
    
    # Generate server certificate and key
    echo -e "\n" | ./easyrsa build-server-full server nopass
    
    # Generate client certificate and key
    echo -e "\n" | ./easyrsa build-client-full $CLIENT_NAME nopass
    
    # Generate Diffie-Hellman parameters
    ./easyrsa gen-dh
    
    # Generate TLS-auth key
    openvpn --genkey secret pki/ta.key
    
    # Copy certificates to OpenVPN directory
    cp pki/ca.crt $OPENVPN_DIR/
    cp pki/issued/server.crt $OPENVPN_DIR/
    cp pki/private/server.key $OPENVPN_DIR/
    cp pki/dh.pem $OPENVPN_DIR/
    cp pki/ta.key $OPENVPN_DIR/
    
    log "PKI configuration completed"
}

create_openvpn_server_config() {
    log "Creating OpenVPN server configuration..."
    
    cat > $OPENVPN_DIR/server.conf << EOF
# OpenVPN Server Configuration
# Generated by VPN Setup Script

port $VPN_PORT
proto udp
dev tun

# SSL/TLS root certificate (ca), certificate (cert), and private key (key)
ca ca.crt
cert server.crt
key server.key
dh dh.pem

# Network topology
topology subnet

# Configure server mode and supply a VPN subnet
server 10.8.0.0 255.255.255.0

# Maintain a record of client <-> virtual IP address associations
ifconfig-pool-persist /var/log/openvpn/ipp.txt

# Push routes to the client to allow it to reach other private subnets
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 8.8.8.8"
push "dhcp-option DNS 8.8.4.4"

# Client-to-client communication
client-to-client

# Keep alive
keepalive 10 120

# TLS security
tls-auth ta.key 0
cipher AES-256-GCM
auth SHA256

# Compression
compress lz4-v2
push "compress lz4-v2"

# Maximum number of concurrently connected clients
max-clients 10

# Run with reduced privileges
user nobody
group nogroup

# Persist keys and tunnel
persist-key
persist-tun

# Output a short status file
status /var/log/openvpn/openvpn-status.log

# Log verbosity
verb 3
explicit-exit-notify 1
EOF

    # Create log directory
    mkdir -p /var/log/openvpn
    
    log "OpenVPN server configuration created"
}

create_openvpn_client_config() {
    log "Creating OpenVPN client configuration..."
    
    mkdir -p /root/vpn-clients
    
    cat > /root/vpn-clients/$CLIENT_NAME.ovpn << EOF
client
dev tun
proto udp
remote $SERVER_IP $VPN_PORT
resolv-retry infinite
nobind
persist-key
persist-tun
cipher AES-256-GCM
auth SHA256
compress lz4-v2
verb 3

<ca>
$(cat $OPENVPN_DIR/easy-rsa/pki/ca.crt)
</ca>

<cert>
$(cat $OPENVPN_DIR/easy-rsa/pki/issued/$CLIENT_NAME.crt)
</cert>

<key>
$(cat $OPENVPN_DIR/easy-rsa/pki/private/$CLIENT_NAME.key)
</key>

<tls-auth>
$(cat $OPENVPN_DIR/ta.key)
</tls-auth>
key-direction 1
EOF

    log "Client configuration created: /root/vpn-clients/$CLIENT_NAME.ovpn"
}

# =============================================================================
# WireGuard Setup Functions
# =============================================================================

install_wireguard() {
    log "Installing WireGuard..."
    
    apt install -y wireguard qrencode
    
    log "WireGuard installed successfully"
}

configure_wireguard() {
    log "Configuring WireGuard..."
    
    # Generate server keys
    wg genkey | tee $WIREGUARD_DIR/private.key | wg pubkey > $WIREGUARD_DIR/public.key
    
    # Generate client keys
    wg genkey | tee $WIREGUARD_DIR/client_private.key | wg pubkey > $WIREGUARD_DIR/client_public.key
    
    # Set permissions
    chmod 600 $WIREGUARD_DIR/private.key $WIREGUARD_DIR/client_private.key
    
    # Read keys
    SERVER_PRIVATE_KEY=$(cat $WIREGUARD_DIR/private.key)
    SERVER_PUBLIC_KEY=$(cat $WIREGUARD_DIR/public.key)
    CLIENT_PRIVATE_KEY=$(cat $WIREGUARD_DIR/client_private.key)
    CLIENT_PUBLIC_KEY=$(cat $WIREGUARD_DIR/client_public.key)
    
    # Create server configuration
    cat > $WIREGUARD_DIR/wg0.conf << EOF
[Interface]
# Server configuration
PrivateKey = $SERVER_PRIVATE_KEY
Address = 10.0.0.1/24
ListenPort = $VPN_PORT
SaveConfig = true

# Enable IP forwarding and NAT
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
# Client configuration
PublicKey = $CLIENT_PUBLIC_KEY
AllowedIPs = 10.0.0.2/32
EOF

    log "WireGuard server configuration created"
}

create_wireguard_client_config() {
    log "Creating WireGuard client configuration..."
    
    mkdir -p /root/vpn-clients
    
    SERVER_PUBLIC_KEY=$(cat $WIREGUARD_DIR/public.key)
    CLIENT_PRIVATE_KEY=$(cat $WIREGUARD_DIR/client_private.key)
    
    cat > /root/vpn-clients/wg0-client.conf << EOF
[Interface]
PrivateKey = $CLIENT_PRIVATE_KEY
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = $SERVER_PUBLIC_KEY
Endpoint = $SERVER_IP:$VPN_PORT
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
EOF

    # Generate QR code for mobile devices
    qrencode -t ansiutf8 < /root/vpn-clients/wg0-client.conf
    qrencode -o /root/vpn-clients/wg0-client-qr.png < /root/vpn-clients/wg0-client.conf
    
    log "WireGuard client configuration created: /root/vpn-clients/wg0-client.conf"
    log "QR code generated: /root/vpn-clients/wg0-client-qr.png"
}

# =============================================================================
# Firewall Configuration
# =============================================================================

configure_firewall() {
    log "Configuring firewall rules..."
    
    # Reset UFW to default
    ufw --force reset
    ufw default deny incoming
    ufw default allow outgoing
    
    # Allow SSH (important!)
    ufw allow ssh
    
    # Allow VPN port
    ufw allow $VPN_PORT/udp
    
    if [[ "$VPN_TYPE" == "openvpn" ]]; then
        # OpenVPN specific rules
        ufw allow in on tun0
        ufw allow out on tun0
        
        # NAT rules for OpenVPN
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
        iptables -A FORWARD -i tun0 -j ACCEPT
        iptables -A FORWARD -o tun0 -j ACCEPT
        
    elif [[ "$VPN_TYPE" == "wireguard" ]]; then
        # WireGuard specific rules
        ufw allow in on wg0
        ufw allow out on wg0
    fi
    
    # Enable UFW
    ufw --force enable
    
    # Save iptables rules
    iptables-save > /etc/iptables/rules.v4
    
    log "Firewall configured successfully"
}

# =============================================================================
# Service Management
# =============================================================================

enable_services() {
    log "Enabling VPN service..."
    
    if [[ "$VPN_TYPE" == "openvpn" ]]; then
        systemctl enable openvpn@server
        systemctl start openvpn@server
        systemctl status openvpn@server --no-pager
        
    elif [[ "$VPN_TYPE" == "wireguard" ]]; then
        systemctl enable wg-quick@wg0
        systemctl start wg-quick@wg0
        systemctl status wg-quick@wg0 --no-pager
    fi
    
    log "VPN service enabled and started"
}

# =============================================================================
# Connection Instructions
# =============================================================================

show_connection_instructions() {
    echo
    echo "=========================================================================="
    echo -e "${GREEN}VPN SERVER SETUP COMPLETE!${NC}"
    echo "=========================================================================="
    echo
    echo -e "${BLUE}Server Details:${NC}"
    echo "  Server IP: $SERVER_IP"
    echo "  VPN Port: $VPN_PORT"
    echo "  VPN Type: $VPN_TYPE"
    echo
    
    if [[ "$VPN_TYPE" == "openvpn" ]]; then
        echo -e "${BLUE}OpenVPN Client Configuration:${NC}"
        echo "  Config file: /root/vpn-clients/$CLIENT_NAME.ovpn"
        echo
        echo -e "${YELLOW}Connection Instructions:${NC}"
        echo
        echo "📱 ${BLUE}Android:${NC}"
        echo "  1. Install 'OpenVPN for Android' from Play Store"
        echo "  2. Copy $CLIENT_NAME.ovpn to your device"
        echo "  3. Import the .ovpn file in the app"
        echo "  4. Connect"
        echo
        echo "🍎 ${BLUE}iOS:${NC}"
        echo "  1. Install 'OpenVPN Connect' from App Store"
        echo "  2. Email the .ovpn file to yourself or use cloud storage"
        echo "  3. Open the file with OpenVPN Connect"
        echo "  4. Import and connect"
        echo
        echo "🪟 ${BLUE}Windows:${NC}"
        echo "  1. Download OpenVPN GUI from https://openvpn.net/community-downloads/"
        echo "  2. Install OpenVPN GUI"
        echo "  3. Copy $CLIENT_NAME.ovpn to C:\\Program Files\\OpenVPN\\config\\"
        echo "  4. Right-click OpenVPN GUI in system tray and connect"
        echo
        echo "🍎 ${BLUE}macOS:${NC}"
        echo "  1. Install Tunnelblick from https://tunnelblick.net/"
        echo "  2. Double-click the .ovpn file to import"
        echo "  3. Connect through Tunnelblick"
        echo
        echo "🐧 ${BLUE}Linux:${NC}"
        echo "  1. Install OpenVPN: sudo apt install openvpn"
        echo "  2. Connect: sudo openvpn --config $CLIENT_NAME.ovpn"
        
    elif [[ "$VPN_TYPE" == "wireguard" ]]; then
        echo -e "${BLUE}WireGuard Client Configuration:${NC}"
        echo "  Config file: /root/vpn-clients/wg0-client.conf"
        echo "  QR Code: /root/vpn-clients/wg0-client-qr.png"
        echo
        echo -e "${YELLOW}Connection Instructions:${NC}"
        echo
        echo "📱 ${BLUE}Android/iOS:${NC}"
        echo "  1. Install 'WireGuard' app from Play Store/App Store"
        echo "  2. Tap '+' and 'Scan from QR code'"
        echo "  3. Scan the QR code displayed above or from the PNG file"
        echo "  4. Toggle the connection on"
        echo
        echo "🪟 ${BLUE}Windows:${NC}"
        echo "  1. Download WireGuard from https://www.wireguard.com/install/"
        echo "  2. Install WireGuard"
        echo "  3. Click 'Import tunnel(s) from file' and select wg0-client.conf"
        echo "  4. Activate the tunnel"
        echo
        echo "🍎 ${BLUE}macOS:${NC}"
        echo "  1. Install WireGuard from Mac App Store"
        echo "  2. Click '+' and 'Import from file'"
        echo "  3. Select wg0-client.conf"
        echo "  4. Activate the tunnel"
        echo
        echo "🐧 ${BLUE}Linux:${NC}"
        echo "  1. Install WireGuard: sudo apt install wireguard"
        echo "  2. Copy config: sudo cp wg0-client.conf /etc/wireguard/"
        echo "  3. Connect: sudo wg-quick up wg0-client"
        echo "  4. Disconnect: sudo wg-quick down wg0-client"
        echo
        echo "📱 ${BLUE}Mobile QR Code:${NC}"
        echo "Scan this QR code with your mobile WireGuard app:"
        qrencode -t ansiutf8 < /root/vpn-clients/wg0-client.conf
    fi
    
    echo
    echo "=========================================================================="
    echo -e "${GREEN}Security Notes:${NC}"
    echo "• Keep your client configuration files secure"
    echo "• Only share them with trusted devices"
    echo "• Regularly update your server and VPN software"
    echo "• Monitor connection logs for suspicious activity"
    echo
    echo -e "${YELLOW}Useful Commands:${NC}"
    
    if [[ "$VPN_TYPE" == "openvpn" ]]; then
        echo "• Check status: sudo systemctl status openvpn@server"
        echo "• View logs: sudo journalctl -u openvpn@server -f"
        echo "• Restart service: sudo systemctl restart openvpn@server"
    elif [[ "$VPN_TYPE" == "wireguard" ]]; then
        echo "• Check status: sudo systemctl status wg-quick@wg0"
        echo "• View logs: sudo journalctl -u wg-quick@wg0 -f"
        echo "• Show peers: sudo wg show"
        echo "• Restart service: sudo systemctl restart wg-quick@wg0"
    fi
    
    echo "• Check firewall: sudo ufw status"
    echo "• Monitor connections: sudo netstat -tulpn | grep $VPN_PORT"
    echo "=========================================================================="
}

# =============================================================================
# Main Menu and Setup
# =============================================================================

show_menu() {
    echo
    echo "=========================================================================="
    echo -e "${GREEN}VPN Server Setup Script${NC}"
    echo "=========================================================================="
    echo
    echo "This script will set up a secure VPN server on Ubuntu 22.04"
    echo
    echo "Choose your VPN type:"
    echo "1) OpenVPN (Traditional, widely supported)"
    echo "2) WireGuard (Modern, faster, simpler)"
    echo "3) Exit"
    echo
}

get_user_input() {
    while true; do
        show_menu
        read -p "Enter your choice (1-3): " choice
        
        case $choice in
            1)
                VPN_TYPE="openvpn"
                VPN_PORT="1194"
                break
                ;;
            2)
                VPN_TYPE="wireguard"
                VPN_PORT="51820"
                break
                ;;
            3)
                echo "Exiting..."
                exit 0
                ;;
            *)
                echo "Invalid option. Please choose 1, 2, or 3."
                ;;
        esac
    done
    
    echo
    read -p "Enter VPN port (default: $VPN_PORT): " custom_port
    if [[ -n "$custom_port" ]]; then
        VPN_PORT="$custom_port"
    fi
    
    read -p "Enter client name (default: $CLIENT_NAME): " custom_client
    if [[ -n "$custom_client" ]]; then
        CLIENT_NAME="$custom_client"
    fi
}

main() {
    log "Starting VPN server setup..."
    
    check_root
    get_user_input
    get_server_ip
    update_system
    enable_ip_forwarding
    
    if [[ "$VPN_TYPE" == "openvpn" ]]; then
        install_openvpn
        configure_openvpn_pki
        create_openvpn_server_config
        create_openvpn_client_config
    elif [[ "$VPN_TYPE" == "wireguard" ]]; then
        install_wireguard
        configure_wireguard
        create_wireguard_client_config
    fi
    
    configure_firewall
    enable_services
    show_connection_instructions
    
    log "VPN setup completed successfully!"
}

# Run main function
main "$@"