#!/bin/bash

# =============================================================================
# WireGuard VPN Server Setup Script for Ubuntu 22.04
# =============================================================================
# This script automatically sets up a secure WireGuard VPN server with:
# - Automatic package installation
# - Random encryption keys generation
# - Client configuration generation
# - Firewall configuration (UFW)
# - Systemd service setup
# - Detailed logging and error handling
# =============================================================================

set -e  # Exit on any error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration variables
VPN_SERVER_IP=""
VPN_PORT="51820"
VPN_INTERFACE="wg0"
VPN_NETWORK="10.0.0.0"
VPN_SUBNET="255.255.255.0"
VPN_DNS1="8.8.8.8"
VPN_DNS2="8.8.4.4"
CLIENT_NAME="client1"
CLIENT_IP="10.0.0.2"

# Logging function
log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}"
}

warn() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING: $1${NC}"
}

error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: $1${NC}"
    exit 1
}

info() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')] INFO: $1${NC}"
}

# Function to check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (use sudo)"
    fi
}

# Function to detect server IP
detect_server_ip() {
    log "Detecting server IP address..."
    
    # Try to get the primary IP address
    if command -v ip &> /dev/null; then
        VPN_SERVER_IP=$(ip route get 8.8.8.8 | awk 'NR==1 {print $7}')
    elif command -v hostname &> /dev/null; then
        VPN_SERVER_IP=$(hostname -I | awk '{print $1}')
    else
        error "Could not detect server IP address"
    fi
    
    if [[ -z "$VPN_SERVER_IP" ]]; then
        error "Could not detect server IP address"
    fi
    
    log "Detected server IP: $VPN_SERVER_IP"
}

# Function to update system packages
update_system() {
    log "Updating system packages..."
    apt update -y || error "Failed to update package list"
    apt upgrade -y || error "Failed to upgrade packages"
    
    # Install essential packages
    log "Installing essential packages..."
    apt install -y curl wget git ufw fail2ban || error "Failed to install essential packages"
}

# Function to install WireGuard
install_wireguard() {
    log "Installing WireGuard..."
    
    # Add WireGuard repository for latest version
    log "Adding WireGuard repository..."
    apt install -y software-properties-common || error "Failed to install software-properties-common"
    add-apt-repository ppa:wireguard/wireguard -y || error "Failed to add WireGuard repository"
    apt update -y || error "Failed to update package list"
    
    # Install WireGuard
    apt install -y wireguard wireguard-tools || error "Failed to install WireGuard"
    
    # Verify installation
    if ! command -v wg &> /dev/null; then
        error "WireGuard installation failed"
    fi
    
    log "WireGuard installed successfully"
}

# Function to generate WireGuard keys
generate_keys() {
    log "Generating WireGuard keys..."
    
    # Create WireGuard directory
    mkdir -p /etc/wireguard
    cd /etc/wireguard
    
    # Generate server keys
    log "Generating server private and public keys..."
    wg genkey | tee privatekey | wg pubkey > publickey || error "Failed to generate server keys"
    
    # Generate client keys
    log "Generating client private and public keys..."
    wg genkey | tee client_privatekey | wg pubkey > client_publickey || error "Failed to generate client keys"
    
    # Set proper permissions
    chmod 600 privatekey
    chmod 600 client_privatekey
    chmod 644 publickey
    chmod 644 client_publickey
    
    # Store keys in variables
    SERVER_PRIVATE_KEY=$(cat privatekey)
    SERVER_PUBLIC_KEY=$(cat publickey)
    CLIENT_PRIVATE_KEY=$(cat client_privatekey)
    CLIENT_PUBLIC_KEY=$(cat client_publickey)
    
    log "WireGuard keys generated successfully"
}

# Function to create WireGuard server configuration
create_server_config() {
    log "Creating WireGuard server configuration..."
    
    cat > /etc/wireguard/$VPN_INTERFACE.conf << EOF
# WireGuard Server Configuration
# Generated by VPN Setup Script

[Interface]
# Server configuration
Address = $VPN_NETWORK.1/24
ListenPort = $VPN_PORT
PrivateKey = $SERVER_PRIVATE_KEY

# Enable IP forwarding
PostUp = iptables -A FORWARD -i $VPN_INTERFACE -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i $VPN_INTERFACE -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# DNS configuration
PostUp = iptables -A FORWARD -o $VPN_INTERFACE -j ACCEPT
PostDown = iptables -D FORWARD -o $VPN_INTERFACE -j ACCEPT

# Client configuration
[Peer]
# $CLIENT_NAME
PublicKey = $CLIENT_PUBLIC_KEY
AllowedIPs = $CLIENT_IP/32
PersistentKeepalive = 25
EOF
    
    # Set proper permissions
    chmod 600 /etc/wireguard/$VPN_INTERFACE.conf
    
    log "Server configuration created successfully"
}

# Function to create client configuration
create_client_config() {
    log "Creating client configuration file..."
    
    # Create client config directory
    mkdir -p /etc/wireguard/client-configs/
    
    cat > /etc/wireguard/client-configs/$CLIENT_NAME.conf << EOF
# WireGuard Client Configuration
# Generated by VPN Setup Script
# Client: $CLIENT_NAME

[Interface]
# Client configuration
Address = $CLIENT_IP/24
PrivateKey = $CLIENT_PRIVATE_KEY
DNS = $VPN_DNS1, $VPN_DNS2

# Prevent DNS leaks
PostUp = resolvectl dns %i $VPN_DNS1 $VPN_DNS2
PostUp = resolvectl domain %i ~.

[Peer]
# Server configuration
PublicKey = $SERVER_PUBLIC_KEY
Endpoint = $VPN_SERVER_IP:$VPN_PORT
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
EOF
    
    # Set proper permissions
    chmod 644 /etc/wireguard/client-configs/$CLIENT_NAME.conf
    
    log "Client configuration created: /etc/wireguard/client-configs/$CLIENT_NAME.conf"
}

# Function to enable IP forwarding
enable_ip_forwarding() {
    log "Enabling IP forwarding..."
    
    # Enable IP forwarding
    echo 'net.ipv4.ip_forward=1' >> /etc/sysctl.conf
    echo 'net.ipv6.conf.all.forwarding=1' >> /etc/sysctl.conf
    sysctl -p || error "Failed to apply sysctl changes"
    
    log "IP forwarding enabled successfully"
}

# Function to configure firewall
configure_firewall() {
    log "Configuring firewall (UFW)..."
    
    # Reset UFW to default
    ufw --force reset || error "Failed to reset UFW"
    
    # Set default policies
    ufw default deny incoming || error "Failed to set default deny incoming"
    ufw default allow outgoing || error "Failed to set default allow outgoing"
    
    # Allow SSH (important to prevent lockout)
    ufw allow ssh || error "Failed to allow SSH"
    
    # Allow WireGuard port
    ufw allow $VPN_PORT/udp || error "Failed to allow WireGuard port"
    
    # Enable UFW
    ufw --force enable || error "Failed to enable UFW"
    
    log "Firewall configured successfully"
}

# Function to create systemd service
create_systemd_service() {
    log "Creating systemd service..."
    
    # Enable WireGuard service
    systemctl enable wg-quick@$VPN_INTERFACE || error "Failed to enable WireGuard service"
    
    log "Systemd service created and enabled"
}

# Function to start WireGuard service
start_wireguard_service() {
    log "Starting WireGuard service..."
    
    wg-quick up $VPN_INTERFACE || error "Failed to start WireGuard interface"
    
    # Check if interface is up
    if ip link show $VPN_INTERFACE &> /dev/null; then
        log "WireGuard interface started successfully"
    else
        error "WireGuard interface failed to start"
    fi
}

# Function to create connection instructions
create_instructions() {
    log "Creating connection instructions..."
    
    cat > /etc/wireguard/client-configs/README.md << EOF
# WireGuard Client Connection Instructions

## Server Information
- Server IP: $VPN_SERVER_IP
- Port: $VPN_PORT
- Protocol: UDP

## Client Configuration File
The client configuration file is: \`$CLIENT_NAME.conf\`

## Connection Instructions by Platform

### Windows
1. Download and install WireGuard from: https://www.wireguard.com/install/
2. Open WireGuard and click "Import tunnel(s) from file"
3. Select the \`$CLIENT_NAME.conf\` file
4. Click "Activate" to connect

### macOS
1. Download and install WireGuard from: https://www.wireguard.com/install/
2. Open WireGuard and click "Import tunnel(s) from file"
3. Select the \`$CLIENT_NAME.conf\` file
4. Click "Activate" to connect

### Linux
1. Install WireGuard: \`sudo apt install wireguard\` (Ubuntu/Debian)
2. Copy the \`$CLIENT_NAME.conf\` file to your home directory
3. Connect: \`sudo wg-quick up ./$CLIENT_NAME.conf\`
4. Disconnect: \`sudo wg-quick down ./$CLIENT_NAME.conf\`

### Android
1. Install WireGuard from Google Play Store
2. Tap the "+" button and select "Create from file"
3. Select the \`$CLIENT_NAME.conf\` file
4. Tap "Activate" to connect

### iOS
1. Install WireGuard from App Store
2. Tap the "+" button and select "Create from file"
3. Select the \`$CLIENT_NAME.conf\` file
4. Tap "Activate" to connect

## Security Notes
- Keep your client configuration file secure
- The VPN will route all traffic through the server
- DNS queries are also routed through the VPN for privacy
- WireGuard uses modern cryptography (ChaCha20, Poly1305, Curve25519)

## Troubleshooting
- Ensure the server IP and port are correct
- Check that your firewall allows the connection
- Verify the client configuration file is complete
- Try different DNS servers if needed

## WireGuard Advantages
- **Faster**: Lower latency and higher throughput
- **Simpler**: Less code, fewer attack vectors
- **Modern**: State-of-the-art cryptography
- **Efficient**: Lower CPU usage
- **Secure**: Built with security in mind
EOF
    
    log "Connection instructions created: /etc/wireguard/client-configs/README.md"
}

# Function to display final information
display_final_info() {
    echo
    echo "============================================================================="
    echo "🎉 WireGuard VPN Server Setup Completed Successfully!"
    echo "============================================================================="
    echo
    echo "📋 Server Information:"
    echo "   • Server IP: $VPN_SERVER_IP"
    echo "   • Port: $VPN_PORT"
    echo "   • Protocol: UDP"
    echo "   • VPN Network: $VPN_NETWORK.0/24"
    echo "   • Client IP: $CLIENT_IP"
    echo
    echo "📁 Important Files:"
    echo "   • Client Config: /etc/wireguard/client-configs/$CLIENT_NAME.conf"
    echo "   • Instructions: /etc/wireguard/client-configs/README.md"
    echo "   • Server Config: /etc/wireguard/$VPN_INTERFACE.conf"
    echo
    echo "🔧 Service Status:"
    echo "   • WireGuard Interface: $(ip link show $VPN_INTERFACE 2>/dev/null | grep -o "state UP" || echo "DOWN")"
    echo "   • UFW Firewall: $(ufw status | grep -o "Status: active")"
    echo
    echo "📱 Next Steps:"
    echo "   1. Download the client configuration file"
    echo "   2. Follow the instructions in the README.md file"
    echo "   3. Test your connection"
    echo
    echo "🔒 Security Features Enabled:"
    echo "   • ChaCha20 encryption"
    echo "   • Poly1305 authentication"
    echo "   • Curve25519 key exchange"
    echo "   • Firewall protection (UFW)"
    echo "   • IP forwarding enabled"
    echo "   • DNS leak protection"
    echo
    echo "⚡ WireGuard Advantages:"
    echo "   • Faster than OpenVPN"
    echo "   • Lower CPU usage"
    echo "   • Modern cryptography"
    echo "   • Simpler configuration"
    echo
    echo "============================================================================="
    echo
}

# Function to add additional clients
add_client() {
    local new_client_name="$1"
    local new_client_ip="$2"
    
    if [[ -z "$new_client_name" ]]; then
        error "Client name is required"
    fi
    
    if [[ -z "$new_client_ip" ]]; then
        # Auto-assign IP based on existing clients
        new_client_ip=$(grep -o "10\.0\.0\.[0-9]*" /etc/wireguard/$VPN_INTERFACE.conf | sort -V | tail -1 | cut -d. -f4)
        new_client_ip=$((new_client_ip + 1))
        new_client_ip="10.0.0.$new_client_ip"
    fi
    
    log "Adding new client: $new_client_name with IP: $new_client_ip"
    
    # Generate new client keys
    cd /etc/wireguard
    wg genkey | tee ${new_client_name}_privatekey | wg pubkey > ${new_client_name}_publickey
    
    # Get the new client's public key
    NEW_CLIENT_PUBLIC_KEY=$(cat ${new_client_name}_publickey)
    
    # Add to server config
    cat >> /etc/wireguard/$VPN_INTERFACE.conf << EOF

[Peer]
# $new_client_name
PublicKey = $NEW_CLIENT_PUBLIC_KEY
AllowedIPs = $new_client_ip/32
PersistentKeepalive = 25
EOF
    
    # Create client config
    NEW_CLIENT_PRIVATE_KEY=$(cat ${new_client_name}_privatekey)
    
    cat > /etc/wireguard/client-configs/$new_client_name.conf << EOF
# WireGuard Client Configuration
# Generated by VPN Setup Script
# Client: $new_client_name

[Interface]
# Client configuration
Address = $new_client_ip/24
PrivateKey = $NEW_CLIENT_PRIVATE_KEY
DNS = $VPN_DNS1, $VPN_DNS2

# Prevent DNS leaks
PostUp = resolvectl dns %i $VPN_DNS1 $VPN_DNS2
PostUp = resolvectl domain %i ~.

[Peer]
# Server configuration
PublicKey = $SERVER_PUBLIC_KEY
Endpoint = $VPN_SERVER_IP:$VPN_PORT
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
EOF
    
    # Set proper permissions
    chmod 600 ${new_client_name}_privatekey
    chmod 644 ${new_client_name}_publickey
    chmod 644 /etc/wireguard/client-configs/$new_client_name.conf
    
    # Reload WireGuard configuration
    wg syncconf $VPN_INTERFACE <(wg-quick strip $VPN_INTERFACE)
    
    log "Client $new_client_name added successfully"
    log "Client config: /etc/wireguard/client-configs/$new_client_name.conf"
}

# Function to show usage
show_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo
    echo "Options:"
    echo "  --add-client NAME [IP]  Add a new client with optional IP"
    echo "  --help                  Show this help message"
    echo
    echo "Examples:"
    echo "  $0                      # Initial setup"
    echo "  $0 --add-client client2 # Add client2 with auto-assigned IP"
    echo "  $0 --add-client client3 10.0.0.5 # Add client3 with specific IP"
}

# Main execution function
main() {
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --add-client)
                if [[ -z "$2" ]]; then
                    error "Client name is required for --add-client"
                fi
                add_client "$2" "$3"
                exit 0
                ;;
            --help)
                show_usage
                exit 0
                ;;
            *)
                error "Unknown option: $1"
                ;;
        esac
        shift
    done
    
    echo "============================================================================="
    echo "🚀 WireGuard VPN Server Setup Script for Ubuntu 22.04"
    echo "============================================================================="
    echo
    
    # Check if running as root
    check_root
    
    # Detect server IP
    detect_server_ip
    
    # Update system
    update_system
    
    # Install WireGuard
    install_wireguard
    
    # Generate keys
    generate_keys
    
    # Create server configuration
    create_server_config
    
    # Create client configuration
    create_client_config
    
    # Enable IP forwarding
    enable_ip_forwarding
    
    # Configure firewall
    configure_firewall
    
    # Create systemd service
    create_systemd_service
    
    # Start WireGuard service
    start_wireguard_service
    
    # Create connection instructions
    create_instructions
    
    # Display final information
    display_final_info
}

# Run main function
main "$@"